### ISSUE TITLE
 Custom subdomain URL

### ISSUE THREAD

**Issue by rafeequl** [code-mancers/dockup#171]
Let's say we want to provide third party / other team a development API. It would be nice if every enhancement go through to the same URL, so the experience would be seamless for them (consumer).
The flow would be something like this :
 
* New dockup instance with `devel.dockup.sleekr.id` url
* New changes available, delete dockup instance
* Deploy new changes with `devel.dockup.sleekr.id` url

However we need to make sure that the URL is unique and valid.

**Comment by emilsoman** [comment]
I agree this can be useful.

Once we have support for k8s backend, we'll be moving towards "projects and images with tags" instead of "projects with git urls and branches". We can support more controlled subdomain naming along with this change. The subdomain could be:

`<service>.<image_tag_name>.<project_name>` .  This would mean that there can only be one deployment of a tag at a time and new deployments would replace the existing deployment after pulling latest changes.

**Comment by rafeequl** [comment]
Looks like k8 will help a lot of things :)

However,
I think having more than 1 tag at a time could be useful also. QA and PO could work on the same branch but with different purpose.

**Comment by iffyuva** [comment]
Right now, we name releases as `dockup1`, `dockup2`, `dockup3` and so on. Maybe we can give optional input to enter name? If no name is given, we will auto fill it. Will this work?

**Comment by emilsoman** [comment]
Done in k8s-ui branch. Waiting for testing and merging.
