### ISSUE TITLE
Trim white spaces off branch names when input in the dockup deployment page

### ISSUE THREAD

**Issue by manuraj17** [code-mancers/dockup#180]
Issue:
In the deployment page when we are asked to input the branch to deploy, if the input has whitespace in the branch name it fails to pick it up. For, eg: ' test_branch' instead of 'test_branch'.

Expected:
The branch should be picked up irrespective of the whitepsaces

**Comment by amit-mb** [comment]
@manuraj17 
This can be fixed by changing the following lines
https://github.com/code-mancers/dockup/blob/3c0bba5a72c2ce6b41f98be3c52cc8a83fe9c54c/apps/dockup_ui/web/static/js/components/deployment_form.js#L65-L69

to

```js
  handleBranchChange(branch) {
    this.setState({branch: branch.trim() });
}
```

The addresses the issue because `.trim()` removes the spaces from both the ends. Also there would be no whitespaces in between as it is a git branch name.

**Comment by emilsoman** [comment]
@manuraj17 there you go, pls submit a PR 👍

**Comment by manuraj17** [comment]
Thanks @amit-mb!
Sure @emilsoman.
